services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin!"
      MYSQL_DATABASE: "mason-async-job-service"
      MYSQL_USER: mason
      MYSQL_PASSWORD: "admin!"
    ports:
      - "3307:3306"
    volumes:
      - async-job-mysql:/var/lib/mysql

volumes:
  async-job-mysql: